font_family      JetBrainsMono NF
font_size        12.0

foreground       #B9DAF8
background       #000000
background_opacity 0.6

selection_foreground #000000
selection_background #B9DAF8
active_border_color   #DBC58F
inactive_border_color #000000

window_padding_width 15
confirm_os_window_close 0
