font_family      JetBrainsMono NF
font_size        12.0

foreground       #B9DAF8
background       #000000
background_opacity 0.6

selection_foreground #000000
selection_background #B9DAF8
active_border_color   #DBC58F
inactive_border_color #000000

window_padding_width 15
confirm_os_window_close 0

### --- Tab Bar Appearance --- ###
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted

### --- Tab Bar Colors --- ###
# The overall background area of the tab bar container
tab_bar_background      #000000

# The currently focused tab (Matching your gold border accent)
active_tab_foreground   #DBC58F 
active_tab_background   #284EC3
active_tab_font_style   bold

# Background tabs waiting in the dark (Matching your standard layout)
inactive_tab_foreground #B9DAF8
inactive_tab_background #1A1A1A
inactive_tab_font_style normal

# When a background tab triggers a process alert or terminal bell
bell_on_tab_color       #FF6C6B
