$background = 131316
$onBackground = e4e2e5
$surface = 131316
$surfaceDim = 131316
$surfaceBright = 39393c
$surfaceContainerLowest = 0e0e10
$surfaceContainerLow = 1b1b1e
$surfaceContainer = 1f1f22
$surfaceContainerHigh = 2a2a2c
$surfaceContainerHighest = 353437
$onSurface = e4e2e5
$surfaceVariant = 45464e
$onSurfaceVariant = c6c6cf
$outline = 909099
$outlineVariant = 45464e
$inverseSurface = e4e2e5
$inverseOnSurface = 303033
$shadow = 000000
$scrim = 000000
$surfaceTint = bac5ee
$primary = bcc7f1
$primaryDim = c8d3fd
$onPrimary = 242f50
$primaryContainer = a1acd4
$onPrimaryContainer = 354062
$inversePrimary = 525d81
$primaryFixed = dbe1ff
$primaryFixedDim = bac5ee
$onPrimaryFixed = 0e1a3a
$onPrimaryFixedVariant = 3b4668
$secondary = c3c6d8
$secondaryDim = dfe1f4
$onSecondary = 2c303e
$secondaryContainer = 424655
$onSecondaryContainer = b1b4c6
$secondaryFixed = dfe1f4
$secondaryFixedDim = c3c6d8
$onSecondaryFixed = 171b28
$onSecondaryFixedVariant = 424655
$tertiary = e4c489
$tertiaryDim = fad99b
$onTertiary = 402d01
$tertiaryContainer = c7a970
$onTertiaryContainer = 523d0e
$tertiaryFixed = ffdea2
$tertiaryFixedDim = e2c287
$onTertiaryFixed = 261900
$onTertiaryFixedVariant = 594314
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 6b769b
$secondaryPaletteKeyColor = 737686
$tertiaryPaletteKeyColor = c7a970
$neutralPaletteKeyColor = 777679
$neutralVariantPaletteKeyColor = 75767e
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 6b769b
$secondary_paletteKeyColor = 737686
$tertiary_paletteKeyColor = c7a970
$neutral_paletteKeyColor = 777679
$neutral_variant_paletteKeyColor = 75767e
$term0 = 353434
$term1 = 957dff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 90acd6
$term5 = a6a2ee
$term6 = 9bcefe
$term7 = e8d3de
$term8 = ac9fa9
$term9 = ae9bff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b0c2db
$term13 = beb8f7
$term14 = bae0ff
$term15 = ffffff
$rosewater = f5eff9
$flamingo = e5dff4
$pink = dbd9ff
$mauve = b3bcff
$red = b2aaff
$maroon = bfb8f0
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = cde1ff
$sky = c8dcff
$sapphire = abc8ff
$blue = a3bbff
$lavender = bdcbff
$klink = 6286d0
$klinkSelection = 6186d0
$kvisited = 6e77dd
$kvisitedSelection = 6d77dd
$knegative = 8972ff
$knegativeSelection = 8872ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 4bb0ff
$kpositiveSelection = 4ab0ff
$text = e4e2e5
$subtext1 = c6c6cf
$subtext0 = 909099
$overlay2 = 7d7d85
$overlay1 = 6a6a71
$overlay0 = 59595f
$surface2 = 48484d
$surface1 = 37373b
$surface0 = 252528
$base = 131316
$mantle = 131316
$crust = 121215
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
