# Keep the preload line as is
preload = /home/Mokshagna/Pictures/Wallpapers/Screenshot_20260304_230547.png


# Use the new block syntax
wallpaper {
    monitor =
    path = /home/Mokshagna/Pictures/Wallpapers/2026-08-24-225202_hyprshot.png
    }

    ipc = on
    splash = false
